version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: amplia
      RABBITMQ_DEFAULT_PASS: ampliatask123.
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ampliadb
      MONGO_INITDB_ROOT_PASSWORD: ampliadbtask123.
      MONGO_INITDB_DATABASE: admin
volumes:
  rabbitmq_data:
  mongodb_data:

